import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import clsx from "clsx";

import { LinkHandler } from "@/components/LinkHandler";
import sharedStyles from "@/asset/css/sharedStyles.module.scss";
import styles from "/src/asset/css/layout.module.scss";
import Link from "next/link";

import { setCssVariables, VARIABLES } from '@/asset/utils/setCssVariables';


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            href="/fonts/nexaBlack.woff2"
            crossOrigin="anonymous"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            href="/fonts/bonVoyage.woff2"
            crossOrigin="anonymous"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            href="/fonts/openSans400.woff2"
            crossOrigin="anonymous"
          />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />

            <script
            dangerouslySetInnerHTML={{
                __html: `(${setCssVariables.toString()})({variables:${JSON.stringify(
                VARIABLES,
                )}})`,
            }}
            />
        </head>

        <body>
        <div className={styles.authorWrapper}>
            <span className={sharedStyles.text}>
                선짱과 함께하는 Tennis Life by
            </span>
            <span className={styles.contactSpacer} />
            <LinkHandler isExternal elHref="https://github.com/tennislife">
                <span className={clsx(
                    sharedStyles.text,
                    sharedStyles.textBold,
                    sharedStyles.textUnderline,
                )}
                >빠진사슴 
                </span>
            </LinkHandler>
        </div>

        <div className={styles.gtiWrapper}>
            <LinkHandler
            isExternal
            elHref="https://github.com/tennislife"
            >
                <span className={clsx(sharedStyles.text, sharedStyles.textUnderline)}>GitHub</span>
            </LinkHandler>
        </div>
        </body>
    </html>
  );
}
